package org.coral.server.game.data.config.pojo;

import java.util.List;
import java.util.Map;

/**
* Do not edit this file by yourself, it must be generated by excelUtils.
* @author Jeremy
*/
public class ConfigConstantPlus  {

	public static int freeBuyGold;//免费购买金币次数
	public static int buyGoldPeriod;//购买金币时间间隔（S）
	public static int dailyFreePk;//竞技场每天免费挑战次数
	public static int dailyFreeDungeon;//日常副本每天免费挑战次数（5种类型的日常副本通用此常量）
	public static Map<Integer,Integer> tempMap;//测试map
	public static List<Integer> tempList;//测试List
	public static int friendsnumber;//好友数
	public static int applyfornumber;//申请数
	public static int blacklistnumber;//黑名单数
	public static Map<Integer,Integer> givingfriendship;//好友赠送礼物奖励
	public static Map<Integer,Integer> getFriendship;//领取礼物奖励
	public static int friendGiftNum;//礼物列表数
	public static int friendGiveNum;//赠礼物送数
	public static int randomFriendNum;//添加好友随机在线玩家数
	public static int chat;//聊天字数限制（50个字）
	public static int expression;//聊天表情上限（5个表情）
	public static int voyageRefreshNum;//远航每天免费刷新次数
	public static int voyageRefreshList;//远航刷新任务列表数
	public static Map<Integer,Integer> voyageRefreshCost;//远航刷新消耗
	public static Map<Integer,Integer> voyageCompleteCostForHour;//远航完成任务每小时消耗
	public static Map<Integer,Integer> voyageHigh;//远航高级特权(刷新次数_任务品质)
	public static Map<Integer,Integer> voyageLuxury;//远航豪华特权(刷新次数_任务品质)
	public static int voyageListNum;//远航接取任务上限
	public static Map<Integer,Integer> voyagevouchers;//刷新任务消耗远航券数量
	public static Map<Integer,Integer> voyage;//刷新远航任务消耗钻石数
	public static int dungeonHookTimeLimit;//主线副本挂机时长限制(秒)
	public static int dungeonMinutesReward;//主线副本快速作战x小时奖励(分钟)
	public static int dungeonQuickFightCount;//主线副本快速战斗默认次数
	public static int dungeonQuickFightBuyCount;//主线副本快速战斗默认购买次数
	public static int dungeonFightBossMinutesReward;//主线副本挑战Boss固定分钟收益
	public static Map<Integer,Integer> luckytreasureonce;//幸运探宝1次消耗
	public static Map<Integer,Integer> luckytreasurefifteentime;//幸运探宝15次消耗
	public static Map<Integer,Integer> advancedsearchonce;//高级探宝1次消耗
	public static Map<Integer,Integer> advancedsearchTentimes;//高级探宝10次消耗
	public static int treasurerefreshtime;//探宝刷新时长
	public static Map<Integer,Integer> treasureintegral;//探宝1次获得的探宝积分
	public static int ordinarycombatfreetimes;//普通快速作战免费次数
	public static int ordinarycomcombatpurchasestimes;//普通快速作战购买次数
	public static int luckyTreasureGetListNum;//玩家抽到稀有物品暂时列表数量
	public static int forgeRuneSmeltValue;//符文熔炼值兑换符文所需熔炼值数量
	public static int forgeRuneSmeltAward;//符文熔炼值兑换符文ID
	public static int treasureLuckyvalue;//探宝幸运值一次10点
	public static int openTreasureFiteenVipLevel;//幸运探宝开启十五次抽取需要的vip等级
	public static int summonRestDay;//免费召唤刷新天数
	public static int summonRestHour;//免费召唤刷的点数(24小时制)
	public static int openIntegralSummon;//开启积分召唤的vip等级
	public static Map<Integer,Integer> treasureRefreshCost;//探宝刷新消耗
	public static Map<Integer,Integer> scoreCallCost;//开启积分召唤需要的积分
	public static int towerFreeNum;//试练塔免费挑战次数
	public static int towerBuyNum;//试练塔可购买次数
	public static Map<Integer,Integer> arenaCost;//竞技场挑战消耗
	public static int arenaInitialFraction;//竞技场初始分数
	public static int arenaSeasonCloseHour;//竞技场赛季结算点数
	public static int arenaSeasonDay;//竞技场赛季持续天数
	public static int arenaLikeTimes;//竞技场每天点赞次数
	public static Map<Integer,Integer> arenaLikeGet;//竞技场点赞获得奖励
	public static int arenaLogNum;//竞技场挑战记录列表数
	public static int lostCD;//星河神殿挑战失败后20S内无法挑战任何神位
	public static int arenaSkipBattleCount;//竞技场开启跳过战斗需要的次数
	public static int arenaUpdateBtnCooling;//竞技场刷新对手按钮冷却时间
	public static int arenaCanRankNum;//竞技场排行榜显示数
	public static Map<Integer,Integer> arenaInitialIntegral;//竞技场初始配置分数
	public static Map<Integer,Integer> artifactStampAttribute;//神器刻印石属性
	public static Map<Integer,Integer> artifactHolySealStampCost;//神器圣印需要刻印石
	public static Map<Integer,Integer> championShipQuizCurrency;//冠军赛竞猜币每次竞猜给60
	public static Map<Integer,Integer> dispersePotionBuy;//驱散药剂购买金额，一次30钻石
	public static int dispersePotionUseCeiling;//驱散药剂使用上限5个
	public static int lifePotionUseCeiling;//生命药剂使用上限5个
	public static int dispersePotionBuyCeiling;//驱散药剂购买上限
	public static List<Integer> endlessInitialStages;//无尽试炼初始配置id
	public static int newbieGuideSkip;//新手引导跳过时间10秒
	public static int newbieGuideDialogue;//新手引导播放对话时间5秒
	public static Map<Integer,Integer> barrageConsumption;//发送弹幕消耗金币5000
	public static Map<Integer,Integer> championShipBet;//冠军赛押注值每次10
	public static Map<Integer,Integer> endlessSupportReward;//无尽试炼支援奖励
	public static int championJoinNum;//冠军赛参加人数
	public static int championReadyTime;//冠军赛准备时间
	public static int championBetTime;//冠军赛下注时间
	public static int championBattleTime;//冠军赛战斗时间
	public static int thirtyDaySecond;//30天倒计时（秒）
	public static Map<Integer,Integer> arenaTicketBuy;//购买竞技场挑战券消耗钻石
	public static Map<Integer,Integer> endlessSupportMailReward;//无尽试炼支援友情奖励点（邮件）
	public static List<Integer> voyageFirstTask;//远航首次刷新任务
	public static int vipInitDisplayListLevel;//vip初始显示的列表的等级

	
}
