package org.coral.server.game.module.mission.domain;

public enum MissionEnum {
	//默认实现
	TYPE_DEFAULT(0),
	//登陆
	TYPE_LOGIN(1),
	//赠送友情点
	TYPE_FRIEND(2),
	//所有召唤
	TYPE_CALL_ALL(3),
	//竞技场挑战
	TYPE_ARENA_FIGHT(4),
	//参与公会副本
	TYPE_GUILD_CHAPTER(5),
	//参与公会副本
	TYPE_GUILD_DONATE(6),
	//远航任务
	TYPE_SAIL_MISSION(7),
	//日常副本
	TYPE_DAILY_MISSION(8),
	//挑战试练塔三次
	TYPE_TOWER_DAILY(9),
	//无尽挑战
	TYPE_ENDLESS_FIGHT(10),
	//快速作战
	TYPE_CHAPTER_QUICK(11),
	//合成装备
	TYPE_EQUIP_COMPOSE(12),
	//精灵商店刷新
	TYPE_SHOP_SPIRIT_FRESHEN(13),
	//合成符文
	TYPE_RUNE_COMPOSE(14),
	//先知召唤
	TYPE_CALL_PROPHET(15),
	//高级幸运探宝
	TYPE_TREASURE(16),
	//精灵商店购买
	TYPE_SHOP_SPIRIT_BUY(17),
	//本服冠军赛竞猜
	TYPE_CHAMPION_GUESS(18),
	//周冠军赛竞猜
	TYPE_CHAMPION_WEEK_GUESS(19),
	//位面征战第一层BOSS
	TYPE_PLANES_ONEFLOOR_BOSS(20),
	//公会战挑战
	TYPE_GUILD_BATTLE(21),
	//公会秘境
	TYPE_GUILD_SECRET_FIGHT(22),
	//跨服天梯挑战
	TYPE_LADDER_CROSS_FIGHT(23),
	//元素圣典挑战
	TYPE_ELEMENT_FIGHT(24),
	//超凡段位赛挑战获胜
	TYPE_COMPETITION_SUPER_WIN(25),
	//玩家等级
	TYPE_PLAYER_LEVEL(26),
	//英雄等级
	TYPE_HERO_LEVEL(27),
	//添加好友
	TYPE_FRIEND_ADD(28),
	//探险击杀守卫
	TYPE_DIVINE_KILLGUARD(29),
	//获得*件*品质装备
	TYPE_EQUIP_GET(30),
	//拥有x个x星武将
	TYPE_HERO_HAVE(31),
	//竞技场积分
	TYPE_ARENA_INTEGRAL(32),
	//竞技场积分
	TYPE_ARENA_RANK(33),
	//接取*色远航任务*次
	TYPE_SAIL_MISSION1(34),
	//献祭英雄
	TYPE_HERO_DECOMPOSE(35),
	//击杀公会boss*次
	TYPE_GUILD_BOSS(36),
	//参与星河神殿
	TYPE_STARRIVER_JOIN(37),
	//战力达到x
	TYPE_POWER(38),
	//PVP战斗跨**战力战胜对手**次
	TYPE_PVP_FIGHT(39),
	//PVP满血战胜战力高于自身的玩家
	TYPE_PVP_FIGHT1(40),
	//PVP中累计使用魔神之锤眩晕敌人
	TYPE_PVP_FIGHT2(41),
	//PVP中单场触发保命/神佑
	TYPE_PVP_FIGHT3(42),
	//PVP单场战斗使用技能复活英雄
	TYPE_PVP_FIGHT4(43),
	//PVP单场战斗累计触发闪避
	TYPE_PVP_FIGHT5(44),
	//PVP中任意英雄单场伤害量达到**
	TYPE_PVP_FIGHT6(45),
	//PVP中任意英雄单场治疗量达到**
	TYPE_PVP_FIGHT7(46),
	//PVP中使用神器累计造成击杀*次
	TYPE_PVP_FIGHT8(47),
	//萌宠收藏中不同的珍品
	TYPE_HOME_GEM(48),
	//萌宠出行时常累计达到**
	TYPE_HOME_JOURNEY(49),
	//萌宠出行带回*色家具*件
	TYPE_HOME_FURNITURE(50),
	//PVP中*回合战胜战力高于自己的对手*次
	TYPE_PVP_FIGHT9(51),
	//冠军赛进入*强*次
	TYPE_CHAMPION_FIGHT(52),
	//参与周冠军赛
	TYPE_CHAMPION_WEEK_JOIN(53),
	//周冠军赛进入*强*次
	TYPE_CHAMPION_WEEK_FIGHT(54),
	//参与巅峰冠军赛
	TYPE_CHAMPION_PEAK_JOIN(55),
	//巅峰冠军赛进入*强*次
	TYPE_CHAMPION_PEAK_FIGHT(56),
	//跨服天梯胜利*次
	TYPE_LADDER_CROSS_WIN(57),
	//跨服天梯结算获得*名
	TYPE_LADDER_CROSS_RANK(58),
	//超凡段位赛赛季结算时达到*段位及以上段位
	TYPE_COMPETITION_SUPER_ORDER(59),
	//超凡段位赛赛季结算时获得*名次
	TYPE_COMPETITION_SUPER_RANK(60),
	//超凡段位赛参与一次王者赛
	TYPE_COMPETITION_SUPER_KING_JOIN(61),
	//跨服竞技场获胜*次数
	TYPE_ARENA_CROSS_WIN(62),
	//跨服竞技场获得*名次
	TYPE_ARENA_CROSS_RANK(63),
	//组队竞技场队伍获胜次数
	TYPE_ARENA_TEAM_WIN(64),
	//队长参与组队竞技场挑战100次
	TYPE_ARENA_TEAM_LEADER_JOIN(65),
	//组队竞技场己方前两位直接击败对方全部选手
	TYPE_ARENA_TEAM_FIGHT(66),
	//组队竞技场结算获得前*，*次
	TYPE_ARENA_TEAM_RANK(67),
	//组队赛首个出战选手击败全部选手*次数
	TYPE_ARENA_TEAM_FIGHT1(68),
	//组队赛最后出战选手击败全部选手*次数
	TYPE_ARENA_TEAM_FIGHT2(69),
	//开启家园
	TYPE_HOME_OPEN(70),
	//获取符文
	TYPE_RUNE_GET(71),
	//拥有跨服好友*个
	TYPE_FRIEND_CROSS(72),
	//使*个水系英雄达到*星
	TYPE_HERO_WATER_UPSTART(73),
	//使*个火系英雄达到*星
	TYPE_HERO_FIRE_UPSTART(74),
	//使*个风系英雄达到*星
	TYPE_HERO_WIND_UPSTART(75),
	//使*个光系英雄达到*星
	TYPE_HERO_LIGHT_UPSTART(76),
	//使*个暗系英雄达到*星
	TYPE_HERO_DARK_UPSTART(77),
	//本服冠军赛竞猜
	TYPE_CHAMPION_GUESS_ALLWIN(78),
	//周冠军赛竞猜
	TYPE_CHAMPION_WEEK_GUESS_ALLWIN(79),
	//巅峰冠军赛竞猜
	TYPE_CHAMPION_PEAK_GUESS_ALLWIN(80),
	//领悟*级天赋技能*个
	TYPE_SKILL_GIFT_GET(81),
	//友情召唤获得*星英雄*个
	TYPE_CALL_FRIEND(82),
	//普通召唤获得*星英雄*个
	TYPE_CALL_NORMAL(83),
	//战斗中累计触发天平模式*次
	TYPE_BATTLE_BALANCE(84),
	//试练塔达到x层
	TYPE_TOWER_PASS(85),
	//单场战斗累计造成**多少，**什么伤害 1=中毒 2=流血 3=灼烧
	TYPE_BATTLE_FIGHT(86),
	//公会副本单场造成**伤害
	TYPE_GUILD_FIGHT(87),
	//公会战获胜*次
	TYPE_GUILD_WIN(88),
	//无尽试炼达到**
	TYPE_ENDLESS(89),
	//通关位面征战第三层*次
	TYPE_PLANES_THREE(90),
	//神界冒险到**层
	TYPE_DIVINE_PASS(91),
	//神界冒险击杀守卫**
	TYPE_DIVINE_KILLGUILD(92),
	//通关任意圣典第*关
	TYPE_ELEMENT_PASS(93),
	//本周内通关每个圣殿第*关
	TYPE_ELEMENT_WEEK_PASS(94),
	//元素圣典排行榜结算获得*次前*名
	TYPE_ELEMENT_RANK(95),
	//完美通关天界副本前*章
	TYPE_HEAVEN_PASS(96),
	//副本通关
	TYPE_CHAPTER_PASS(97),
	//高级召唤
	TYPE_CALL_HIGH(98),
	//合成五星英雄
	TYPE_HERO_COMPOSE(99),
	//升级公会技能
	TYPE_GUILD_SKILL_UPLEVEL(100),
	//公会商店消费
	TYPE_GUILD_SHOP_BUY(101),
	//金币捐献
	TYPE_GUILD_DONATE_GOLD(102),
	//钻石捐献
	TYPE_GUILD_DONATE_INGOT(103),
	//至尊钻石捐献
	TYPE_GUILD_DONATE_MAXINGOT(104),
	//发送红包

	//公会副本加成
	TYPE_GUILD_DUNGEON_ADDBUFF(106);
	;
	
	private int type;
	
	private MissionEnum(int type) {
		this.type = type;
	}

	public int getType() {
		return type;
	}

	public final static MissionEnum[] VALUE_SAVE= {TYPE_POWER,TYPE_CHAPTER_PASS,TYPE_TOWER_PASS,TYPE_ENDLESS,TYPE_DIVINE_PASS};
	public static MissionEnum getEnum(int completeType) {
		for(MissionEnum type:values()) {
			if(type.getType()==completeType)
				return type;
		}
		return null;
	}
	
}
